home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('alternate-diceware/', views.dice, name="whatever"),
    path('bash', views.bash, name="bash"),
]

kitchen_memo/urls.py
from django.urls import path
from . import views

app_name = 'kitchen_memo'
urlpatterns = [
    path('', views.index, name='home'),
    path('all/', views.all, name="all_recipes"),
    path('search_recipes/', views.search, name="search_recipes"),
    path('add/', views.add, name="add_recipe"),
    path('edit/<int:recipe_id>/', views.edit, name="edit_recipe"),
    path('recipe/<int:recipe_id>/', views.recipe, name="recipe"),
    path('memo/<int:recipe_id>/', views.memo, name="memo"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('home.urls')),
    path('japanese/', include('japanese.urls')),
    path('timeline/', include('timeline.urls')),
    path('kitchen_memo/', include('kitchen_memo.urls')),
    path('admin/', admin.site.urls),
]

kitchen_memo/models.py
from django.db import models

# Create your models here.

class Recipe(models.Model):
    name = models.CharField(max_length=200)
    link = models.CharField(max_length=2000, blank=True)
    instructions = models.TextField(blank=True)

    def __str__(self):
        return self.name

class Tag(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    tag_text = models.CharField(max_length=200)

    def __str__(self):
        return self.tag_text

class Memo(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    date = models.DateField()
    memo_text = models.TextField()
    rating = models.CharField(max_length=2)

    def __str__(self):
        return str(self.date) + str(self.recipe)

kitchen_memo/forms.py
from django.forms import ModelForm
from .models import Recipe

class RecipeForm(ModelForm):
    class Meta:
        model = Recipe
        fields = ['name', 'link', 'instructions']

kitchen_memo/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.urls import reverse

default_tags = {
    'meals': [
        {
            'html_name': 'breakfast',
            'display_name': 'Breakfast'
        },
        {
            'html_name': 'lunch',
            'display_name': 'Lunch'
        },
        {
            'html_name': 'dinner',
            'display_name': 'Dinner'
        },

    ],
    'protein': [
        {
            'html_name': 'beef',
            'display_name': 'Beef',
        },
        {
            'html_name': 'salmon',
            'display_name': 'Salmon',
        },
        {
            'html_name': 'pork',
            'display_name': 'Pork',
        },
        {
            'html_name': 'shrimp',
            'display_name': 'Shrimp',
        },
        {
            'html_name': 'chicken',
            'display_name': 'Chicken'
        },
    ]
}

def index(request):
    return render(request, 'kitchen_memo/index.html')

def all(request):
    from kitchen_memo.models import Recipe, Tag
    print(Recipe.objects.all())
    recipes = Recipe.objects.all()
    context = {
        'recipes': Recipe.objects.all(),
    }
    return render(request, 'kitchen_memo/all_recipes.html', context)

def search(request):
    return render(request, 'kitchen_memo/search_recipes.html')

def add(request):
    from kitchen_memo.forms import RecipeForm
    form = RecipeForm()
    if request.method == "POST":
        from kitchen_memo.models import Recipe, Tag
        form = RecipeForm(request.POST)
        if form.is_valid():
            r = Recipe(name=request.POST['name'], link=request.POST['link'], instructions=request.POST['instructions'])
            r.save()
            tag_list = request.POST.getlist('tags[]')
            for tag in request.POST.getlist('tags[]'):
                t = Tag(recipe=r, tag_text=tag)
                t.save()
            redirect_url = '/kitchen_memo/recipe/' + str(r.id)
            return HttpResponseRedirect(redirect_url)
        else:
            print(form.errors)
    context = {
        'form': form
    }

    return render(request, 'kitchen_memo/add_recipe.html', context)

def edit(request, recipe_id):
    from kitchen_memo.models import Recipe
    this_recipe = Recipe.objects.get(id=recipe_id)
    from kitchen_memo.forms import RecipeForm
    form = RecipeForm()
    if request.method == "POST":
        from kitchen_memo.models import Recipe, Tag
        form = RecipeForm(request.POST)
        if form.is_valid():
            this_recipe.name = request.POST['name']
            this_recipe.link = request.POST['link']
            this_recipe.instructions = request.POST['instructions']
            this_recipe.save()
            for tag in request.POST.getlist('tags[]'):
                print('i think were not getting here')
                t = Tag(recipe=this_recipe, tag_text=tag)
                t.save()
            redirect_url = '/kitchen_memo/recipe/' + str(this_recipe.id)
            return HttpResponseRedirect(redirect_url)
    from kitchen_memo.models import Tag
    tags = Tag.objects.filter(recipe=this_recipe)
    checkboxes = {}
    tag_strings = []
    for tag in tags:
        tag_strings.append(tag.tag_text)
        checkboxes[tag.tag_text] = 'checked'
    for section in default_tags:
        for tag in default_tags[section]:
            if tag['html_name'] in tag_strings:
                tag['checked'] = 'checked'

    context = {
        'form': form,
        'recipe': this_recipe,
        'default_tags': default_tags,
        'checkboxes': checkboxes
    }
    return render(request, 'kitchen_memo/edit_recipe.html', context)

def recipe(request, recipe_id):
    from kitchen_memo.models import Recipe
    this_recipe = Recipe.objects.filter(id=recipe_id)[0]
    print(this_recipe)
    from kitchen_memo.models import Tag
    tags = Tag.objects.filter(recipe=this_recipe)
    context = {
        'recipe': this_recipe,
        'tags': tags
    }
    return render(request, 'kitchen_memo/recipe.html', context)

def memo(request, recipe_id):
    return HttpResponse("You're looking at question %s." % recipe_id)

kitchen_memo/templates/kitchen_memo/add_recipe.html
{% extends "kitchen_memo/base.html" %}

{% block title %} Add New Recipe {% endblock %}

{% block head_extra %}
{% load static %}
<link rel='stylesheet' href='{% static 'kitchen_memo/recipe_form.css' %} '>
{% endblock head_extra %}

{% block content %}
<header>
  <h1>Add New Recipe</h1>
</header>
<main>
  <form method="POST" id="recipe-form">
    {% csrf_token %}
    <div style="display:inline-block">
      <label for="recipe-name">Name:</label>{{ form.name.errors }}
    </div>
    <input type="text" id="recipe-name" name="name">
    <label for="recipe-link">Link:</label>
    {{ form.link.errors }}
    <input type="text" id="recipe-link" name="link">
    <label for="recipe-text">Recipe:</label>
    {{ form.instructions.errors }}
    <textarea id="recipe-text" rows=10 cols=33 name="instructions"></textarea>
    <div id="tags">
      <section>
        <input type="checkbox" id="breakfast" name="tags[]" value="breakfast">
        <label for="breakfast">Breakfast</label><br>
        <input type="checkbox" id="lunch" name="tags[]" value="lunch">
        <label for="lunch">Lunch</label><br>
        <input type="checkbox" id="dinner" name="tags[]" value="dinner">
        <label for="dinner">Dinner</label><br>
        <input type="checkbox" id="drink" name="tags[]" value="drink">
        <label for="drink">Drink</label><br>
        <input type="checkbox" id="dessert" name="tags[]" value="dessert">
        <label for="dessert">Dessert</label><br>
        <input type="checkbox" id="seasoning" name="tags[]" value="seasoning">
        <label for="seasoning">Seasoning</label><br>
      </section>
      <section>
        <input type="checkbox" id="beef" name="tags[]" value="beef">
        <label for="beef">Beef</label><br>
        <input type="checkbox" id="salmon" name="tags[]" value="salmon">
        <label for="salmon">Salmon</label><br>
        <input type="checkbox" id="pork" name="tags[]" value="pork">
        <label for="pork">Pork</label><br>
        <input type="checkbox" id="shrimp" name="tags[]" value="shrimp">
        <label for="shrimp">Shrimp</label><br>
        <input type="checkbox" id="chicken" name="tags[]" value="chicken">
        <label for="chicken">Chicken</label>
      </section>
      <section>
        <input type="checkbox" id="stove-top" name="tags[]" value="stove-top">
        <label for="stove-top">Stove top</label><br>
        <input type="checkbox" id="pressure-cook" name="tags[]" value="pressure-cook">
        <label for="pressure-cook">Pressure cook</label><br>
        <input type="checkbox" id="slow-cook" name="tags[]" value="slow-cook">
        <label for="slow-cook">Slow cook</label><br>
        <input type="checkbox" id="oven-bake" name="tags[]" value="oven-bake">
        <label for="oven-bake">Oven bake</label><br>
      </section>
      <section>
        <input type="checkbox" id="tomato" name="tags[]" value="tomato">
        <label for="tomato">Tomato</label><br>
        <input type="checkbox" id="curry" name="tags[]" value="curry">
        <label for="spinach">Spinach</label><br>
        <input type="checkbox" id="egg" name="tags[]" value="egg">
        <label for="egg">Egg</label><br>
      </section>
      <section>
        <input type="checkbox" id="lime" name="tags[]" value="lime">
        <label for="lime">Lime</label><br>
        <input type="checkbox" id="lemon" name="tags[]" value="lemon">
        <label for="lemon">Lemon</label><br>
      </section>
      <section>
        <input type="checkbox" id="mayonnaise" name="tags[]" value="mayonnaise">
        <label for="mayonnaise">Mayonnaise</label><br>
        <input type="checkbox" id="sour-cream" name="tags[]" value="sour-cream">
        <label for="sour-cream">Sour Cream</label><br>
      </section>
      <section>
        <input type="checkbox" id="curry" name="tags[]" value="curry">
        <label for="curry">Curry</label><br>
      </section>
      <section>
        <label for="new-tag">New tag:</label><br>
        <input type="text" id="new-tag" name="new-tag" value="">
      </section>
    </div>
    <input type="submit" value="Submit">
  </form>
</main>
{% endblock %}

kitchen_memo/templates/kitchen_memo/all_recipes.html
{% extends "kitchen_memo/base.html" %}

{% block title %} All Recipes {% endblock %}

{% block content %}

    <header>
      <h1> All Recipes </h1>
    </header>
    <main>
      {% for recipe in recipes %}
      <div>
        <a href="{% url 'kitchen_memo:recipe' recipe.id %}">{{ recipe }}</a>
        </a>
      </div>
      <div>
      </div>
      {% endfor %}
    </main>

{% endblock %}

kitchen_memo/templates/kitchen_memo/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Kitchen Memo{% endblock %}</title>
    {% load static %}
    <link rel='stylesheet' href='{% static 'kitchen_memo/style.css' %} '>
    <link rel='stylesheet' href='{% static 'kitchen_memo/sidebar.css' %} '>
    {% block head_extra %}{% endblock %}
  </head>
  <body>
    <div class="sidebar">
      <a id="logo-anchor" href="{% url 'kitchen_memo:home' %}"><img href="{% url 'kitchen_memo:all_recipes' %}" id="navbar-logo" src="{% static 'kitchen_memo/cover.png' %} " alt=""></a>
      <a href="{% url 'kitchen_memo:all_recipes' %}">View all recipes</a>
      <a href="{% url 'kitchen_memo:add_recipe' %}">Add new recipe</a>
      <a href="{% url 'kitchen_memo:search_recipes' %}">Search for recipes</a>
      <a href="#">Settings</a>
      <a href="#">About</a>
    </div>
    <div class="content">
      {% block content %} {% endblock %}
    </div>
  </body>
</html>

kitchen_memo/templates/kitchen_memo/edit_recipe.html
{% extends "kitchen_memo/base.html" %}

{% block title %} Edit Recipe {% endblock %}

{% block head_extra %}
{% load static %}
<link rel='stylesheet' href='{% static 'kitchen_memo/recipe_form.css' %} '>
{% endblock head_extra %}

{% block content %}

    <header>
      <h1> Edit Recipe {{ recipe }}</h1>
    </header>
    <main>
  <form method="POST" id="recipe-form">
      {% include "kitchen_memo/recipe_form.html" %}
  </form>
    </main>

{% endblock %}

kitchen_memo/templates/kitchen_memo/index.html
{% extends "kitchen_memo/base.html" %}

{% block title %} Homepage {% endblock %}

{% block content %}

    <header>
      <h1> Home Page </h1>
    </header>
    <main>
      {% for recipe in recipes %}
      <div>
        <a href="{% url 'kitchen_memo:recipe' recipe.id %}">{{ recipe }}</a>
        </a>
      </div>
      <div>
      </div>
      {% endfor %}
    </main>

{% endblock %}

kitchen_memo/templates/kitchen_memo/recipe.html
{% extends "kitchen_memo/base.html" %}

{% block title %} All Recipes {% endblock %}

{% block content %}
    <header>
      <h1>{{ recipe }}</h1>
      {% if recipe.link %}
      <div><a href="{{ link }}">Source</a></div>
      {% endif %}
      <a href="{% url 'kitchen_memo:edit_recipe' recipe.id %}">Edit</a>
    </header>
    <main>
      <div style="white-space: pre;">{{ recipe.instructions }}</div>
      <br>
      <br>
      
      {% for tag in tags %}
      <div style="border: 1px solid gray">
        {{ tag.tag_text }}
      </div>
      {% endfor %}
    </main>
{% endblock %}

kitchen_memo/templates/kitchen_memo/recipe_form.html
    {% csrf_token %}
    <input type="text" id="recipe-id" name="id" value="{{ recipe.id }}" readonly hidden>
    <div style="display:inline-block">
      <label for="recipe-name">Name:</label>{{ form.name.errors }}
    </div>
    <input type="text" id="recipe-name" name="name" value="{{ recipe.name }}">
    <label for="recipe-link">Source:</label>
    {{ form.link.errors }}
    <input type="text" id="recipe-link" name="link" value="{{ recipe.link }}">
    <label for="recipe-text">Recipe:</label>
    {{ form.instructions.errors }}
    <textarea id="recipe-text" rows=10 cols=33 name="instructions">{{ recipe.instructions }}</textarea>
    <div id="tags">
      <section>
        {% for tag in default_tags.meals %}
          <input type="checkbox" id="{{ tag.html_name }}" name="tags[]" value="{{ tag.html_name }}" {{ tag.checked }}>
          <label for="breakfast">{{ tag.display_name }}</label><br>
        {% endfor %}
      </section>
      <section>
        <input type="checkbox" id="beef" name="tags[]" value="beef">
        <label for="beef">Beef</label><br>
        <input type="checkbox" id="salmon" name="tags[]" value="salmon">
        <label for="salmon">Salmon</label><br>
        <input type="checkbox" id="pork" name="tags[]" value="pork">
        <label for="pork">Pork</label><br>
        <input type="checkbox" id="shrimp" name="tags[]" value="shrimp">
        <label for="shrimp">Shrimp</label><br>
        <input type="checkbox" id="chicken" name="tags[]" value="chicken">
        <label for="chicken">Chicken</label>
      </section>
      <section>
        <input type="checkbox" id="stove-top" name="tags[]" value="stove-top">
        <label for="stove-top">Stove top</label><br>
        <input type="checkbox" id="pressure-cook" name="tags[]" value="pressure-cook">
        <label for="pressure-cook">Pressure cook</label><br>
        <input type="checkbox" id="slow-cook" name="tags[]" value="slow-cook">
        <label for="slow-cook">Slow cook</label><br>
        <input type="checkbox" id="oven-bake" name="tags[]" value="oven-bake">
        <label for="oven-bake">Oven bake</label><br>
      </section>
      <section>
        <input type="checkbox" id="tomato" name="tags[]" value="tomato">
        <label for="tomato">Tomato</label><br>
        <input type="checkbox" id="curry" name="tags[]" value="curry">
        <label for="spinach">Spinach</label><br>
        <input type="checkbox" id="egg" name="tags[]" value="egg">
        <label for="egg">Egg</label><br>
      </section>
      <section>
        <input type="checkbox" id="lime" name="tags[]" value="lime">
        <label for="lime">Lime</label><br>
        <input type="checkbox" id="lemon" name="tags[]" value="lemon">
        <label for="lemon">Lemon</label><br>
      </section>
      <section>
        <input type="checkbox" id="mayonnaise" name="tags[]" value="mayonnaise">
        <label for="mayonnaise">Mayonnaise</label><br>
        <input type="checkbox" id="sour-cream" name="tags[]" value="sour-cream">
        <label for="sour-cream">Sour Cream</label><br>
      </section>
      <section>
        <input type="checkbox" id="curry" name="tags[]" value="curry">
        <label for="curry">Curry</label><br>
      </section>
      <section>
        <label for="new-tag">New tag:</label><br>
        <input type="text" id="new-tag" name="new-tag" value="">
      </section>
    </div>
    <input type="submit" value="Submit">
  </form>

kitchen_memo/templates/kitchen_memo/search_recipes.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title></title>
</head>
<body>
  search recipes
</body>
</html>